# Data Profiling Report - Part 1.A: Dataset Structure

Dataset: French Road Safety Open Data, year 2024 (accidents corporels).

This notebook loads the four raw tables (`caract`, `lieux`, `vehicules`, `usagers`)
and documents their structure: column names, data types, and the semantic meaning
of each column based on the official data.gouv.fr documentation.

Missing values, consistency checks and the overall data quality summary are
covered separately in `02_data_quality.ipynb`.

In [1]:
import pandas as pd
from pathlib import Path

BRONZE_DIR = Path("data/bronze")
FILES = ["caract-2024.csv", "lieux-2024.csv", "vehicules-2024.csv", "usagers-2024.csv"]

## Column descriptions

In [2]:
COLUMN_DESCRIPTIONS = {
    "caract-2024.csv": {
        "Num_Acc": "Unique accident identifier",
        "jour": "Day of the accident",
        "mois": "Month of the accident",
        "an": "Year of the accident",
        "hrmn": "Time of the accident (HH:MM)",
        "lum": "Lighting conditions code",
        "dep": "Department code",
        "com": "Commune (city) code",
        "agg": "Location type: 1 outside urban area, 2 inside urban area",
        "int": "Intersection type code",
        "atm": "Atmospheric/weather conditions code",
        "col": "Type of collision code",
        "adr": "Postal address of the accident",
        "lat": "Latitude of the accident",
        "long": "Longitude of the accident",
    },
    "lieux-2024.csv": {
        "Num_Acc": "Unique accident identifier",
        "catr": "Road category code",
        "voie": "Road number or name",
        "v1": "Numeric road index",
        "v2": "Alphanumeric road index",
        "circ": "Traffic regime code",
        "nbv": "Number of traffic lanes",
        "vosp": "Reserved lane code (bike lane, bus lane)",
        "prof": "Road profile code (flat, slope, hill top, valley)",
        "pr": "Distance marker number (PR)",
        "pr1": "Distance in meters from the PR marker",
        "plan": "Road layout code (straight, curve)",
        "lartpc": "Width of the central reservation in meters",
        "larrout": "Width of the roadway in meters",
        "surf": "Road surface condition code",
        "infra": "Infrastructure or development code",
        "situ": "Position of the accident on the road code",
        "vma": "Maximum authorized speed at the accident location",
    },
    "vehicules-2024.csv": {
        "Num_Acc": "Unique accident identifier",
        "id_vehicule": "Unique vehicle identifier",
        "num_veh": "Vehicle identifier within the accident (A01, B01, ...)",
        "senc": "Direction of travel code",
        "catv": "Vehicle category code",
        "obs": "Fixed obstacle hit code",
        "obsm": "Moving obstacle hit code",
        "choc": "Initial point of impact code",
        "manv": "Main maneuver before the accident code",
        "motor": "Engine type code",
        "occutc": "Number of occupants in a public transport vehicle",
    },
    "usagers-2024.csv": {
        "Num_Acc": "Unique accident identifier",
        "id_usager": "Unique user identifier",
        "id_vehicule": "Vehicle identifier the user was in",
        "num_veh": "Vehicle identifier within the accident",
        "place": "Seat position of the user in the vehicle",
        "catu": "User category: 1 driver, 2 passenger, 3 pedestrian, 4 pedestrian on personal mobility device",
        "grav": "Injury severity: 1 unharmed, 2 killed, 3 hospitalized injured, 4 slightly injured",
        "sexe": "Sex of the user: 1 male, 2 female",
        "an_nais": "Birth year of the user",
        "trajet": "Reason for the trip code",
        "secu1": "First safety equipment code",
        "secu2": "Second safety equipment code",
        "secu3": "Third safety equipment code",
        "locp": "Pedestrian location code",
        "actp": "Pedestrian action code",
        "etatp": "Whether the pedestrian was alone or in a group code",
    },
}

## Load the raw tables

In [3]:
tables = {
    name: pd.read_csv(BRONZE_DIR / name, sep=";", encoding="utf-8", low_memory=False)
    for name in FILES
}

for name, df in tables.items():
    print(name, df.shape)

caract-2024.csv (54402, 15)
lieux-2024.csv (70248, 18)
vehicules-2024.csv (92678, 11)
usagers-2024.csv (125187, 16)

## Column inventory and data types

In [4]:
def column_inventory(name, df):
    descriptions = COLUMN_DESCRIPTIONS.get(name, {})
    return pd.DataFrame({
        "column": df.columns,
        "dtype": [str(df[col].dtype) for col in df.columns],
        "description": [descriptions.get(col, "") for col in df.columns],
    })

inventories = {name: column_inventory(name, df) for name, df in tables.items()}

In [5]:
print("caract-2024.csv")
inventories["caract-2024.csv"]

caract-2024.csv

     column   dtype                                        description
0   Num_Acc   int64                         Unique accident identifier
1      jour   int64                                Day of the accident
2      mois   int64                              Month of the accident
3        an   int64                               Year of the accident
4      hrmn  object                       Time of the accident (HH:MM)
5       lum   int64                           Lighting conditions code
6       dep  object                                    Department code
7       com  object                                Commune (city) code
8       agg   int64  Location type: 1 outside urban area, 2 inside ...
9       int   int64                             Intersection type code
10      atm   int64                Atmospheric/weather conditions code
11      col   int64                             Type of collision code
12      adr  object                     Postal address of the accident
13      lat  object                           Latitude of the accident
14     long  object                          Longitude of the accident

In [6]:
print("lieux-2024.csv")
inventories["lieux-2024.csv"]

lieux-2024.csv

     column   dtype                                        description
0   Num_Acc   int64                         Unique accident identifier
1      catr   int64                                 Road category code
2      voie  object                                Road number or name
3        v1   int64                                 Numeric road index
4        v2  object                            Alphanumeric road index
5      circ   int64                                Traffic regime code
6       nbv  object                            Number of traffic lanes
7      vosp   int64           Reserved lane code (bike lane, bus lane)
8      prof   int64  Road profile code (flat, slope, hill top, valley)
9        pr  object                        Distance marker number (PR)
10      pr1  object              Distance in meters from the PR marker
11     plan   int64                 Road layout code (straight, curve)
12   lartpc  object         Width of the central reservation in meters
13  larrout  object                     Width of the roadway in meters
14     surf   int64                        Road surface condition code
15    infra   int64                 Infrastructure or development code
16     situ   int64          Position of the accident on the road code
17      vma   int64  Maximum authorized speed at the accident location

In [7]:
print("vehicules-2024.csv")
inventories["vehicules-2024.csv"]

vehicules-2024.csv

         column    dtype                                        description
0       Num_Acc    int64                         Unique accident identifier
1   id_vehicule   object                          Unique vehicle identifier
2       num_veh   object  Vehicle identifier within the accident (A01, B...
3          senc    int64                           Direction of travel code
4          catv    int64                              Vehicle category code
5           obs    int64                            Fixed obstacle hit code
6          obsm    int64                           Moving obstacle hit code
7          choc    int64                       Initial point of impact code
8          manv    int64             Main maneuver before the accident code
9         motor    int64                                   Engine type code
10       occutc  float64  Number of occupants in a public transport vehicle

In [8]:
print("usagers-2024.csv")
inventories["usagers-2024.csv"]

usagers-2024.csv

         column    dtype                                        description
0       Num_Acc    int64                         Unique accident identifier
1     id_usager   object                             Unique user identifier
2   id_vehicule   object                 Vehicle identifier the user was in
3       num_veh   object             Vehicle identifier within the accident
4         place    int64           Seat position of the user in the vehicle
5          catu    int64  User category: 1 driver, 2 passenger, 3 pedest...
6          grav    int64  Injury severity: 1 unharmed, 2 killed, 3 hospi...
7          sexe    int64                  Sex of the user: 1 male, 2 female
8       an_nais  float64                             Birth year of the user
9        trajet    int64                           Reason for the trip code
10        secu1    int64                        First safety equipment code
11        secu2    int64                       Second safety equipment code
12        secu3    int64                        Third safety equipment code
13         locp    int64                           Pedestrian location code
14         actp   object                             Pedestrian action code
15        etatp    int64  Whether the pedestrian was alone or in a group...

## Takeaways

Put together, these four tables form a relational structure built around
`Num_Acc`: `caract` describes the accident itself (when, where, under what
conditions), `lieux` describes the road it happened on, `vehicules` lists
every vehicle involved, and `usagers` lists every person involved along with
how badly they were hurt. Almost none of the columns are free text - they are
compact integer codes - which keeps the raw files small but means every
column is unreadable on its own without the description mapping built above.
That also explains why a code like `-1` ("not specified") can hide inside a
column without ever looking like a missing value: it is a perfectly valid
integer, just not a meaningful one. That is exactly the kind of thing the
data quality notebook checks for next.